{% set name = "pyspainmobility" %}
{% set version = "1.1.1" %}
{% set python_min = "3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyspainmobility-{{ version }}.tar.gz
  sha256: bb85e83555dec3124a115119a79bfa2482c25684791d6d384e30496a6fa33577

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - geopandas >=1.0.1,<1.1.dev0
    - tqdm >=4.0.0
    - matplotlib-base >=3.0.0
    - pyarrow >=8.0.0
    - dask >=2024.0

test:
  imports:
    - pyspainmobility
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}


about:
  home: https://github.com/pySpainMobility/pySpainMobility
  summary: Library for downloading and processing Spanish mobility data from MITMA
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CiroBen99
