# conda-recipes/pyspainmobility/meta.yaml
package:
  name: pyspainmobility
  version: "0.1.0"

source:
  git_url: https://github.com/ssai-trento/pySpainMobility.git
  git_rev: v0.1.0

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.7
    - pandas~=2.2.3
    - geopandas~=1.0.1
    - pyarrow>=8.0.0    
    - tqdm >=4.0.0

test:
  imports:
    - pyspainmobility

about:
  home: https://github.com/ssai-trento/pySpainMobility
  license: MIT
  summary: "Tools for downloading and processing Spanish mobility data from MITMA"
  author: "Massimiliano Luca"
  author_email: "mluca@fbk.eu"
