{% set name = "pyspainmobility" %}
{% set version = "2.1.0" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyspainmobility-{{ version }}.tar.gz
  sha256: 2f08fce67698ba533598a89ba6953f1f7d234fb312ca6cf79eac12b09a207e68

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - geopandas-base >=1.1.4,<1.2
    - pyogrio >=0.7.2
    - pyproj >=3.5
    - pandas >=2.0
    - tqdm >=4.0.0
    - polars >=1.25,<2
    - scipy >=1.11

test:
  imports:
    - pyspainmobility
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}


about:
  home: https://github.com/pySpainMobility/pySpainMobility
  summary: Library for downloading and processing Spanish mobility data from MITMA
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CiroBen99
